# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField(default='')),
                ('apellidos', models.TextField(default='')),
                ('telefono', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField(default='')),
                ('apellidos', models.TextField(default='')),
                ('telefono', models.TextField(default='')),
                ('usuario', models.TextField(default='', unique='True')),
                ('clave', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechain', models.DateField()),
                ('horain', models.TimeField()),
                ('fechaout', models.DateField()),
                ('horaout', models.TimeField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipovehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('CA', 'Carro'), ('MO', 'Moto')], max_length=2)),
                ('tarifa', models.IntegerField()),
                ('posiciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(default='', max_length=7)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkapp.clientes')),
                ('tipovehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkapp.tipovehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='vehiculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkapp.vehiculos'),
        ),
    ]
