# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='clientes',
        ),
        migrations.DeleteModel(
            name='clientes',
        ),
    ]
