# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0002_auto_20171104_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='horain',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='horaout',
        ),
    ]
