# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0003_auto_20171104_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fechain',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fechaout',
            field=models.DateTimeField(),
        ),
    ]
