# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0004_auto_20171104_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovehiculo',
            name='descripcion',
            field=models.CharField(choices=[('CA', 'Carro'), ('MO', 'Moto'), ('BI', 'Bicicleta')], max_length=2),
        ),
    ]
