# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0005_auto_20171106_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
