# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0006_ticket_estado'),
        ('parkapp', '0005_auto_20171106_2106'),
    ]

    operations = [
    ]
